### ISSUE TITLE
Halo MCC - Cannot convert these types - Compiling error

### ISSUE THREAD

**Issue by RadOcta** [BlueSkyDefender/Depth3D#68]
After attempting to install from both the reshade installer as well from downloading the shader through the github, I keep having this error.

![image](https://user-images.githubusercontent.com/20705005/181006189-6a147a8f-71c5-4621-a7c8-c6b21f9476c3.png)

**Comment by BlueSkyDefender** [comment]
I will fix this in a few days. Thank you for telling me.

**Comment by BlueSkyDefender** [comment]
Ya, I am going to update the Shader tomorrow. I had to rewrite, move, test
the code, and update the profile.

This game takes long since it's 6 games in one.

The last Halo game halo 4 look the best. Reach has issues with the weapon
hand. Halo CE is basically fine. Halo 2 has issues when going in to the old
mode. Halo 4 needless needles is not in depth.

May not be the best showing for the Shader but at least it works.

Keep in mind online gameplay will not work and if you're going to do co-op
is the optional reshade that lets you do online play. But, you will have to
disable anti-cheat for that.

Actually really like Halo 4 lost track of time playing that for a while.

For sure tomorrow I'll release it.

**Comment by BlueSkyDefender** [comment]
![image](https://user-images.githubusercontent.com/16185319/182507870-363480ea-8b7f-4ab9-9f4c-942545a5f866.png)
Image here Has the location of the Profiles that you need to set per game. 

Also this above issue is solved.

**Comment by RadOcta** [comment]
Appreciated!
