### ISSUE TITLE
No Real Stereo Depth on Hogwarts Legacy OR Stray

### ISSUE THREAD

**Issue by raeldor** [BlueSkyDefender/Depth3D#87]
I tried this with 2 games, but there's no real stereo depth perception.  I thought this would render the left and right eyes from separate camera angles; am I expecting too much?  Or am I doing something wrong?  I tried playing with the settings, but nothing seemed to work.

**Comment by BlueSkyDefender** [comment]
Hogwarts Legacy and Stray are supported.

Uses that can cause depth buffer not to be loaded by ReShade. Can be do to MSAA or other scaling effects effecting the Depth Buffer Addon.

Extended AR Heuristics may need to be enabled if you are using DLSS / FSR/ XeSS.

Also if the shader was not installed properly then it will not auto load Profiles.

Best to download the shader in most cases from ReShade.me and it's installer.

**Comment by raeldor** [comment]
Thanks for the reply.  I think it was my unrealistic expectations.  The stereo separation doesn't appear to be as big as a geometry based approach, I'm guessing because you don't know what to fill in behind the objects.  Is there any way to use a DLSS-like machine learning based approach for reconstruction?

**Comment by BlueSkyDefender** [comment]
> 

You can increase it pass 100 to 125% But, in turn, there more artifacts because of the larger amount of missing information to fill in. 

It sound to me your are looking for exaggerated depth.  Increasing Separation will also increase the sense of depth as well as perspective. You can also adjust perspective, Do not touch ZPD if you made modification to this you may be limiting depth. Reset Shader back to Defaults.

ML would be costly for now and the AI needs to be trained on that kind of thing so it can be useful.

Your guess are wrong BTW. The infilling only effects how the empty space is masked. The Depth generation it self can be set to high values. But, there are heuristics to limit it. Because, the shader it self has built in protections against abnormal settings. If a game has a profile. 

But, this has a indirect limit. The more you increase depth the more the infilling needs to compensate.  

Looks like the Hogwarts Legacy profile needs a slight adjustment. Redownload the shader and Reset the settings.

**Comment by raeldor** [comment]
I really appreciate the detailed response, this is great information.  Interestingly Acer have managed to create an AI based stereo 3d solution called Spatial Labs, though obviously their resources are huge.  Of course it's to support their own 3D displays and I can't see them releasing a generic solution based on it because they want to sell hardware.

I'll definitely re-download and give Hogwarts Legacy another try.  Thank you!

**Comment by BlueSkyDefender** [comment]
Feel free to ask for help.
